@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Jun 01 13:05:20 +0100 2024
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim tb_MVM1_top_behav -key {Behavioral:sim_1:Functional:tb_MVM1_top} -tclbatch tb_MVM1_top.tcl -view D:/project_2/simulation_result/svd_kernel_tb_behav.wcfg -view D:/project_2/tb_MVM1_ctrl_behav.wcfg -log simulate.log"
call xsim  tb_MVM1_top_behav -key {Behavioral:sim_1:Functional:tb_MVM1_top} -tclbatch tb_MVM1_top.tcl -view D:/project_2/simulation_result/svd_kernel_tb_behav.wcfg -view D:/project_2/tb_MVM1_ctrl_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
