# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# IP: ip/s_pruned_2/s_pruned_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==s_pruned_2 || ORIG_REF_NAME==s_pruned_2} -quiet] -quiet

# IP: ip/s_pruned_1/s_pruned_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==s_pruned_1 || ORIG_REF_NAME==s_pruned_1} -quiet] -quiet

# IP: ip/blk_mem_3/blk_mem_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_3 || ORIG_REF_NAME==blk_mem_3} -quiet] -quiet

# IP: ip/fix_add_32/fix_add_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fix_add_32 || ORIG_REF_NAME==fix_add_32} -quiet] -quiet

# IP: ip/fix_acc_32/fix_acc_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fix_acc_32 || ORIG_REF_NAME==fix_acc_32} -quiet] -quiet

# IP: ip/fix_add_16/fix_add_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fix_add_16 || ORIG_REF_NAME==fix_add_16} -quiet] -quiet

# IP: ip/fix_acc_16/fix_acc_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fix_acc_16 || ORIG_REF_NAME==fix_acc_16} -quiet] -quiet
