# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param power.BramSDPPropagationFix 1
set_param chipscope.maxJobs 3
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xczu7ev-ffvc1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/project_2/project_2.cache/wt [current_project]
set_property parent.project_path D:/project_2/project_2.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu104:part0:1.1 [current_project]
set_property ip_output_repo d:/project_2/project_2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{c:/Users/Justin Huang/Downloads/u.coe}}
add_files {{c:/Users/Justin Huang/Downloads/v.coe}}
add_files {{c:/Users/Justin Huang/Downloads/x.coe}}
add_files {{c:/Users/Justin Huang/Downloads/u 1.coe}}
add_files {{c:/Users/Justin Huang/Downloads/v 1.coe}}
add_files {{c:/Users/Justin Huang/Downloads/x 1.coe}}
add_files {{c:/Users/Justin Huang/Downloads/u 2.coe}}
add_files {{c:/Users/Justin Huang/Downloads/v 2.coe}}
add_files {{c:/Users/Justin Huang/Downloads/s 2.coe}}
add_files {{c:/Users/Justin Huang/Downloads/mask_v_1.coe}}
add_files {{c:/Users/Justin Huang/Downloads/mask_v_2.coe}}
add_files {{c:/Users/Justin Huang/Downloads/mask_u_1.coe}}
add_files {{c:/Users/Justin Huang/Downloads/mask_u_2.coe}}
add_files {{c:/Users/Justin Huang/Downloads/s_pruned_1.coe}}
add_files {{c:/Users/Justin Huang/Downloads/s_pruned_2.coe}}
add_files {{c:/Users/Justin Huang/Downloads/u_pruned_1.coe}}
add_files {{c:/Users/Justin Huang/Downloads/u_pruned_2.coe}}
add_files {{c:/Users/Justin Huang/Downloads/v_pruned_1.coe}}
add_files {{c:/Users/Justin Huang/Downloads/v_pruned_2.coe}}
add_files {{c:/Users/Justin Huang/Downloads/input_vector.coe}}
add_files {{c:/Users/Justin Huang/Downloads/tile_size_2/input_vector_tile_size_2.coe}}
add_files {{c:/Users/Justin Huang/Downloads/tile_size_2/s_pruned_1.coe}}
add_files {{c:/Users/Justin Huang/Downloads/tile_size_2/s_pruned_2.coe}}
add_files {{c:/Users/Justin Huang/Downloads/tile_size_2/mask_u_1.coe}}
add_files {{c:/Users/Justin Huang/Downloads/tile_size_2/mask_u_2.coe}}
add_files {{c:/Users/Justin Huang/Downloads/tile_size_2/mask_v_1.coe}}
add_files {{c:/Users/Justin Huang/Downloads/tile_size_2/mask_v_2.coe}}
add_files {{c:/Users/Justin Huang/Downloads/tile2/mask_v.coe}}
add_files {{c:/Users/Justin Huang/Downloads/tile2/mask_u.coe}}
add_files {{c:/Users/Justin Huang/Downloads/tile2/u_pruned_tile_size_2.coe}}
add_files {{c:/Users/Justin Huang/Downloads/tile2/v_pruned_tile_size_2.coe}}
add_files {{c:/Users/Justin Huang/Downloads/tile2/s_pruned_tile_size_2.coe}}
add_files {{c:/Users/Justin Huang/Downloads/tile2/input_vector_tile_size_2.coe}}
add_files {{c:/Users/Justin Huang/Downloads/Single/input_vector.coe}}
add_files {{c:/Users/Justin Huang/Downloads/Single/mask_u.coe}}
add_files {{c:/Users/Justin Huang/Downloads/Single/mask_v.coe}}
add_files {{c:/Users/Justin Huang/Downloads/Single/s_pruned.coe}}
add_files {{c:/Users/Justin Huang/Downloads/Single/u_pruned.coe}}
add_files {{c:/Users/Justin Huang/Downloads/Single/v_pruned.coe}}
read_verilog -library xil_defaultlib {
  D:/project_2/project_2.srcs/sources_1/new/MVM1_2_2.v
  D:/project_2/project_2.srcs/sources_1/new/MVM1_4_2.v
  D:/project_2/project_2.srcs/sources_1/new/MVM1_4_4.v
  D:/project_2/project_2.srcs/sources_1/new/MVM1_ctrl.v
  D:/project_2/project_2.srcs/sources_1/new/MVM1_top.v
  D:/project_2/project_2.srcs/sources_1/new/MVM2_2_2.v
  D:/project_2/project_2.srcs/sources_1/new/MVM2_4_2.v
  D:/project_2/project_2.srcs/sources_1/new/MVM2_4_4.v
  D:/project_2/project_2.srcs/sources_1/new/MVM2_top.v
  D:/project_2/project_2.srcs/sources_1/new/MVM3_2_2.v
  D:/project_2/project_2.srcs/sources_1/new/MVM3_4_2.v
  D:/project_2/project_2.srcs/sources_1/new/MVM3_top.v
  D:/project_2/project_2.srcs/sources_1/new/MVM_1.v
  D:/project_2/project_2.srcs/sources_1/new/MVM_ctrl1.v
  D:/project_2/project_2.srcs/sources_1/new/MVM_ctrl2.v
  D:/project_2/project_2.srcs/sources_1/new/db_mask_u.v
  D:/project_2/project_2.srcs/sources_1/new/db_mask_v.v
  D:/project_2/project_2.srcs/sources_1/new/db_u_tile.v
  D:/project_2/project_2.srcs/sources_1/new/db_v_pruned.v
  D:/project_2/project_2.srcs/sources_1/new/ddr_mask_u.v
  D:/project_2/project_2.srcs/sources_1/new/ddr_mask_v.v
  D:/project_2/project_2.srcs/sources_1/new/ddr_s_tile.v
  D:/project_2/project_2.srcs/sources_1/new/ddr_u_tile.v
  D:/project_2/project_2.srcs/sources_1/new/ddr_v_tile.v
  D:/project_2/project_2.srcs/sources_1/new/input_vector_buffer.v
  D:/project_2/project_2.srcs/sources_1/new/input_vector_input.v
  D:/project_2/project_2.srcs/sources_1/new/mask2addr.v
  D:/project_2/project_2.srcs/sources_1/new/mask2addr_v2.v
  D:/project_2/project_2.srcs/sources_1/new/mask_reverse.v
  D:/project_2/project_2.srcs/sources_1/new/ram_adder.v
  D:/project_2/project_2.srcs/sources_1/new/ram_adder_128.v
  D:/project_2/project_2.srcs/sources_1/new/ram_adder_32.v
  D:/project_2/project_2.srcs/sources_1/new/s_kernel.v
  D:/project_2/project_2.srcs/sources_1/new/s_kernel_32.v
  D:/project_2/project_2.srcs/sources_1/new/svd_kernel.v
  D:/project_2/project_2.srcs/sources_1/new/svd_kernel_128.v
  D:/project_2/project_2.srcs/sources_1/new/svd_kernel_128_4_2.v
  D:/project_2/project_2.srcs/sources_1/new/svd_kernel_128_4_4.v
  D:/project_2/project_2.srcs/sources_1/new/svd_kernel_3.v
  D:/project_2/project_2.srcs/sources_1/new/svd_kernel_32.v
  D:/project_2/project_2.srcs/sources_1/new/svd_kernel_3_4_2.v
  D:/project_2/project_2.srcs/sources_1/new/svd_kernel_3_4_4.v
  D:/project_2/project_2.srcs/sources_1/new/svd_kernel_4_2.v
  D:/project_2/project_2.srcs/sources_1/new/svd_kernel_4_4.v
  D:/project_2/project_2.srcs/sources_1/new/svd_kernel_fsm.v
  D:/project_2/project_2.srcs/sources_1/new/u_kernel.v
  D:/project_2/project_2.srcs/sources_1/new/u_kernel_32.v
  D:/project_2/project_2.srcs/sources_1/new/v_kernel.v
  D:/project_2/project_2.srcs/sources_1/new/v_kernel_32.v
  D:/project_2/project_2.srcs/sources_1/new/v_kernel_4.v
  D:/project_2/project_2.srcs/sources_1/new/MVM3_4_4.v
  D:/project_2/project_2.srcs/sources_1/new/ram_adder_test.v
}
read_ip -quiet D:/project_2/project_2.srcs/sources_1/ip/s_pruned_2/s_pruned_2.xci
set_property used_in_implementation false [get_files -all d:/project_2/project_2.srcs/sources_1/ip/s_pruned_2/s_pruned_2_ooc.xdc]

read_ip -quiet D:/project_2/project_2.srcs/sources_1/ip/s_pruned_1/s_pruned_1.xci
set_property used_in_implementation false [get_files -all d:/project_2/project_2.srcs/sources_1/ip/s_pruned_1/s_pruned_1_ooc.xdc]

read_ip -quiet D:/project_2/project_2.srcs/sources_1/ip/blk_mem_3/blk_mem_3.xci
set_property used_in_implementation false [get_files -all d:/project_2/project_2.srcs/sources_1/ip/blk_mem_3/blk_mem_3_ooc.xdc]

read_ip -quiet D:/project_2/project_2.srcs/sources_1/ip/fix_add_32/fix_add_32.xci
set_property used_in_implementation false [get_files -all d:/project_2/project_2.srcs/sources_1/ip/fix_add_32/fix_add_32_ooc.xdc]

read_ip -quiet D:/project_2/project_2.srcs/sources_1/ip/fix_acc_32/fix_acc_32.xci
set_property used_in_implementation false [get_files -all d:/project_2/project_2.srcs/sources_1/ip/fix_acc_32/fix_acc_32_ooc.xdc]

read_ip -quiet D:/project_2/project_2.srcs/sources_1/ip/fix_add_16/fix_add_16.xci
set_property used_in_implementation false [get_files -all d:/project_2/project_2.srcs/sources_1/ip/fix_add_16/fix_add_16_ooc.xdc]

read_ip -quiet D:/project_2/project_2.srcs/sources_1/ip/fix_acc_16/fix_acc_16.xci
set_property used_in_implementation false [get_files -all d:/project_2/project_2.srcs/sources_1/ip/fix_acc_16/fix_acc_16_ooc.xdc]

read_ip -quiet D:/project_2/project_2.srcs/sources_1/ip/fix_mult_16/fix_mult_16.xci
set_property used_in_implementation false [get_files -all d:/project_2/project_2.srcs/sources_1/ip/fix_mult_16/fix_mult_16_ooc.xdc]

read_ip -quiet D:/project_2/project_2.srcs/sources_1/ip/fix_acc_16_sset/fix_acc_16_sset.xci
set_property used_in_implementation false [get_files -all d:/project_2/project_2.srcs/sources_1/ip/fix_acc_16_sset/fix_acc_16_sset_ooc.xdc]

read_ip -quiet D:/project_2/project_2.srcs/sources_1/ip/blk_mem_2/blk_mem_2.xci
set_property used_in_implementation false [get_files -all d:/project_2/project_2.srcs/sources_1/ip/blk_mem_2/blk_mem_2_ooc.xdc]

read_ip -quiet D:/project_2/project_2.srcs/sources_1/ip/fifo1/fifo1.xci
set_property used_in_implementation false [get_files -all d:/project_2/project_2.srcs/sources_1/ip/fifo1/fifo1.xdc]
set_property used_in_implementation false [get_files -all d:/project_2/project_2.srcs/sources_1/ip/fifo1/fifo1_ooc.xdc]

read_ip -quiet D:/project_2/project_2.srcs/sources_1/ip/blk_mem_true_dual_1/blk_mem_true_dual_1.xci
set_property used_in_implementation false [get_files -all d:/project_2/project_2.srcs/sources_1/ip/blk_mem_true_dual_1/blk_mem_true_dual_1_ooc.xdc]

read_ip -quiet D:/project_2/project_2.srcs/sources_1/ip/blk_mem_u/blk_mem_u.xci
set_property used_in_implementation false [get_files -all d:/project_2/project_2.srcs/sources_1/ip/blk_mem_u/blk_mem_u_ooc.xdc]

read_ip -quiet D:/project_2/project_2.srcs/sources_1/ip/v_tile_ram/v_tile_ram.xci
set_property used_in_implementation false [get_files -all d:/project_2/project_2.srcs/sources_1/ip/v_tile_ram/v_tile_ram_ooc.xdc]

read_ip -quiet D:/project_2/project_2.srcs/sources_1/ip/x_tile_ram/x_tile_ram.xci
set_property used_in_implementation false [get_files -all d:/project_2/project_2.srcs/sources_1/ip/x_tile_ram/x_tile_ram_ooc.xdc]

read_ip -quiet D:/project_2/project_2.srcs/sources_1/ip/fix_mult_32/fix_mult_32.xci
set_property used_in_implementation false [get_files -all d:/project_2/project_2.srcs/sources_1/ip/fix_mult_32/fix_mult_32_ooc.xdc]

read_ip -quiet D:/project_2/project_2.srcs/sources_1/ip/u_tile_ram/u_tile_ram.xci
set_property used_in_implementation false [get_files -all d:/project_2/project_2.srcs/sources_1/ip/u_tile_ram/u_tile_ram_ooc.xdc]

read_ip -quiet D:/project_2/project_2.srcs/sources_1/ip/s_tile_ram/s_tile_ram.xci
set_property used_in_implementation false [get_files -all d:/project_2/project_2.srcs/sources_1/ip/s_tile_ram/s_tile_ram_ooc.xdc]

read_ip -quiet D:/project_2/project_2.srcs/sources_1/ip/blk_mem_1/blk_mem_1.xci
set_property used_in_implementation false [get_files -all d:/project_2/project_2.srcs/sources_1/ip/blk_mem_1/blk_mem_1_ooc.xdc]

read_ip -quiet D:/project_2/project_2.srcs/sources_1/ip/mask_v_1/mask_v_1.xci
set_property used_in_implementation false [get_files -all d:/project_2/project_2.srcs/sources_1/ip/mask_v_1/mask_v_1_ooc.xdc]

read_ip -quiet D:/project_2/project_2.srcs/sources_1/ip/mask_v_2/mask_v_2.xci
set_property used_in_implementation false [get_files -all d:/project_2/project_2.srcs/sources_1/ip/mask_v_2/mask_v_2_ooc.xdc]

read_ip -quiet D:/project_2/project_2.srcs/sources_1/ip/mask_u_1/mask_u_1.xci
set_property used_in_implementation false [get_files -all d:/project_2/project_2.srcs/sources_1/ip/mask_u_1/mask_u_1_ooc.xdc]

read_ip -quiet D:/project_2/project_2.srcs/sources_1/ip/mask_u_2/mask_u_2.xci
set_property used_in_implementation false [get_files -all d:/project_2/project_2.srcs/sources_1/ip/mask_u_2/mask_u_2_ooc.xdc]

read_ip -quiet D:/project_2/project_2.srcs/sources_1/ip/db_u_tile_ram/db_u_tile_ram.xci
set_property used_in_implementation false [get_files -all d:/project_2/project_2.srcs/sources_1/ip/db_u_tile_ram/db_u_tile_ram_ooc.xdc]

read_ip -quiet D:/project_2/project_2.srcs/sources_1/ip/db_v_tile_ram/db_v_tile_ram.xci
set_property used_in_implementation false [get_files -all d:/project_2/project_2.srcs/sources_1/ip/db_v_tile_ram/db_v_tile_ram_ooc.xdc]

read_ip -quiet D:/project_2/project_2.srcs/sources_1/ip/ram_mask_v/ram_mask_v.xci
set_property used_in_implementation false [get_files -all d:/project_2/project_2.srcs/sources_1/ip/ram_mask_v/ram_mask_v_ooc.xdc]

read_ip -quiet D:/project_2/project_2.srcs/sources_1/ip/ram_mask_u/ram_mask_u.xci
set_property used_in_implementation false [get_files -all d:/project_2/project_2.srcs/sources_1/ip/ram_mask_u/ram_mask_u_ooc.xdc]

read_ip -quiet D:/project_2/project_2.srcs/sources_1/ip/ram_u_tile/ram_u_tile.xci
set_property used_in_implementation false [get_files -all d:/project_2/project_2.srcs/sources_1/ip/ram_u_tile/ram_u_tile_ooc.xdc]

read_ip -quiet D:/project_2/project_2.srcs/sources_1/ip/ram_v_tile/ram_v_tile.xci
set_property used_in_implementation false [get_files -all d:/project_2/project_2.srcs/sources_1/ip/ram_v_tile/ram_v_tile_ooc.xdc]

read_ip -quiet D:/project_2/project_2.srcs/sources_1/ip/ram_s_tile/ram_s_tile.xci
set_property used_in_implementation false [get_files -all d:/project_2/project_2.srcs/sources_1/ip/ram_s_tile/ram_s_tile_ooc.xdc]

read_ip -quiet D:/project_2/project_2.srcs/sources_1/ip/ram_input_vector/ram_input_vector.xci
set_property used_in_implementation false [get_files -all d:/project_2/project_2.srcs/sources_1/ip/ram_input_vector/ram_input_vector_ooc.xdc]

read_ip -quiet d:/project_2/project_2.srcs/sources_1/ip/ram_test/ram_test.xci
set_property used_in_implementation false [get_files -all d:/project_2/project_2.srcs/sources_1/ip/ram_test/ram_test_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/project_2/project_2.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files D:/project_2/project_2.srcs/constrs_1/new/constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top ram_adder_test -part xczu7ev-ffvc1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ram_adder_test.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ram_adder_test_utilization_synth.rpt -pb ram_adder_test_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
